// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220519163529_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Meal", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cartofi Prajiti",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orez",
                            Price = 4.25
                        },
                        new
                        {
                            Id = 3,
                            Name = "Piept de pui",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cotlet de porc",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pula de pui dezosata",
                            Price = 4.25
                        },
                        new
                        {
                            Id = 6,
                            Name = "Supa de pui",
                            Price = 3.25
                        },
                        new
                        {
                            Id = 7,
                            Name = "Supa de legume",
                            Price = 3.25
                        });
                });

            modelBuilder.Entity("Domain.Entities.Menu", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("Day")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MealId1")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId10")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId2")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId3")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId4")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId5")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId6")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId7")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId8")
                        .HasColumnType("bit");

                    b.Property<bool?>("MealId9")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MealId1 = true,
                            MealId10 = false,
                            MealId2 = false,
                            MealId3 = true,
                            MealId4 = true,
                            MealId5 = false,
                            MealId6 = false,
                            MealId7 = false,
                            MealId8 = false,
                            MealId9 = false
                        },
                        new
                        {
                            Id = 2,
                            Day = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MealId1 = false,
                            MealId10 = false,
                            MealId2 = true,
                            MealId3 = false,
                            MealId4 = false,
                            MealId5 = true,
                            MealId6 = false,
                            MealId7 = true,
                            MealId8 = false,
                            MealId9 = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfDelivery = new DateTime(2022, 5, 18, 19, 35, 28, 786, DateTimeKind.Local).AddTicks(7296),
                            MealId = 2,
                            Quantity = 1,
                            Status = 1,
                            StudentId = 1,
                            TotalPrice = 4.25
                        },
                        new
                        {
                            Id = 2,
                            DateOfDelivery = new DateTime(2022, 5, 19, 19, 35, 28, 786, DateTimeKind.Local).AddTicks(7379),
                            MealId = 1,
                            Quantity = 2,
                            Status = 0,
                            StudentId = 1,
                            TotalPrice = 8.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdNumber")
                        .IsUnique()
                        .HasFilter("[IdNumber] IS NOT NULL");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "olga.culeac@student.upt.ro",
                            IdNumber = "lm-12314",
                            Name = "Olga Culeac"
                        },
                        new
                        {
                            Id = 2,
                            Email = "banana.banan@gmail.com",
                            IdNumber = "lm-12312S",
                            Name = "Banana banana"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Meal", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Orders")
                        .WithMany("Meals")
                        .HasForeignKey("OrdersId");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
